### ISSUE TITLE
Parse error for example on llhd.io and code generated from Moore

### ISSUE THREAD

**Issue by rachitnigam** [fabianschuiki/llhd-sim#9] opened 2020-06-29 03:19 UTC
Reproduction steps:
1. Install moore and llhd-sim from cargo: `cargo install moore llhd-sim`.
2. Versions reported: llhd-sim (0.3.1), moore (0.10.0)
3. Run llhd-sim on attached llhd example.
4. Run moore on `out.sv` to generate llhd code and run it through llhd-sim.

Error message:
```
Parse error at line: 1, column: 85
Unexpected `-`
Expected `(`
```

[example.llhd.txt](https://github.com/fabianschuiki/llhd-sim/files/4843599/example.llhd.txt)
[out.sv.txt](https://github.com/fabianschuiki/llhd-sim/files/4843601/out.sv.txt)

**Comment by fabianschuiki** [comment] 2020-07-04 08:46
Thanks for the bug report! This is caused by llhd-sim using an outdated version of LLHD; will be fixed as part of #8.

**Comment by fabianschuiki** [comment] 2020-08-26 09:41
This repository is now deprecated in favor of the implementation within LLHD. Tracking continues there. This bug should have been fixed as part of the migration there.

**Closed as completed by fabianschuiki** 2020-08-26 09:41 UTC
Labels: bug, duplicate
